# Generated by Django 4.0.3 on 2022-04-13 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=64)),
                ('text_answer', models.TextField()),
                ('publicate_date', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('likes_ans', models.CharField(max_length=5)),
                ('dislikes_ans', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_quest', models.CharField(max_length=256)),
                ('text_quest', models.TextField()),
                ('publicate_date', models.DateField(blank=True, null=True)),
                ('author', models.CharField(max_length=64)),
                ('likes_quest', models.CharField(max_length=5)),
                ('dislikes_quest', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('y', 'Resolved'), ('n', 'Not_resolved')], max_length=1)),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.answer')),
            ],
        ),
        migrations.CreateModel(
            name='TagQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('m', 'On_moderation'), ('p', 'Published'), ('b', 'Banned')], max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='app.tagquestion'),
        ),
    ]
